### ISSUE TITLE
View Landing page

### ISSUE THREAD

**Issue by Ihret** [FH-Joanneum-Iron-Road-for-Children/iron-road-for-children-web#16]
# Description
As user, I want to have  a landing page to be able to go/navigate to all places.

# Acceptance criteria
- Todo
- as ui example

# Possible way to test
Todo by developer
1. navigation (home, Programm, Voting)
2. navigation (logout)

**Comment by Ihret** [comment]
![image](https://user-images.githubusercontent.com/80459638/226717603-da7a3869-9990-494b-9d18-28402e081d7a.png)

**Comment by KatarinaBorovsak** [comment]
After disscusion with UX/UI team, we decided, that landing page is not neccessary. After login user comes directly on program page. Landing page will not be developed.
