### ISSUE TITLE
View Program List with Weekdays

### ISSUE THREAD

**Issue by Gerw4ld** [FH-Joanneum-Iron-Road-for-Children/iron-road-for-children-web#28]

**Comment by Gerw4ld** [comment]
https://www.figma.com/proto/Io6VFJo035Fe2JJ6LnFhPI/WEB?scaling=scale-down&page-id=0%3A1&starting-point-node-id=2%3A2&node-id=3-3

**Comment by Ihret** [comment]
![image](https://user-images.githubusercontent.com/80459638/232425048-713758dd-1b6e-4aea-9dbe-9d087a1eb57d.png)
