### ISSUE TITLE
[Bug] Angular is not set-up to stable version

### ISSUE THREAD

**Issue by Gerw4ld** [FH-Joanneum-Iron-Road-for-Children/iron-road-for-children-web#36]
# Describe the bug
Angular 15.2.4 is not LTS

# To Reproduce
look at version in package.json

# Expected behavior
Angular set-up that works properly. Downgrade to 14.2.11 LTS.

**Comment by bognern** [comment]
The Angular version is still set to `15.2.4` on `develop` but it looks like it will go into LTS in about two weeks.

![image](https://user-images.githubusercontent.com/127208234/235403440-0b3aba8f-2e7a-4992-b4fa-c5bbd2abc9bb.png)
[Angular](https://angular.io/guide/releases)
