### ISSUE TITLE
[Bug] angular comands do not work on cli

### ISSUE THREAD

**Issue by Ihret** [FH-Joanneum-Iron-Road-for-Children/iron-road-for-children-web#55]
# Describe the bug
it should be possible to create components and services and other angular "stuff" via cli (if you are in src/app)

# To Reproduce
1. open cli
2. navigate to subfolder src/app
3. enter in cli ' ng generate component any-name
4. error is thrown, that the cli do not know this comand

# Expected behavior
a new component and the special dependencies will be generated

# Screenshots

![image](https://user-images.githubusercontent.com/80459638/232517822-60ebb7fd-bfca-4c41-af67-8b77b07b0b52.png)

**Comment by bognern** [comment]
To fix this you can either use a different CLI (bash, cmd) or change your PowerShell execution policy like the error message suggests.

Run PowerShell as Admin: 
`Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser`

[Stackoverflow](https://stackoverflow.com/questions/4037939/powershell-says-execution-of-scripts-is-disabled-on-this-system/4038991)
[Microsoft about_Execution_Policies](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.3)
