### ISSUE TITLE
[US] adapt "add Voting"

### ISSUE THREAD

**Issue by ElenaSchnedlitz** [FH-Joanneum-Iron-Road-for-Children/iron-road-for-children-web#98]
# Description

As an user I want to choose from a list of events to edit a voting.

# Acceptance criteria
 - an array of events is shown instead of strings in the dialog
 - the user can choose from this list

# Possible way to test

Todo by developer

1. ...
2. ...

See:
![image](https://github.com/FH-Joanneum-Iron-Road-for-Children/iron-road-for-children-web/assets/80330151/c669905d-217a-4b44-8cd1-ef6aa748288f)

**Comment by Gerw4ld** [comment]
![image](https://github.com/FH-Joanneum-Iron-Road-for-Children/iron-road-for-children-web/assets/80465751/7f4a6e60-1438-4108-8af0-b3ab7b145bfa)

I also adjusted the buttons to always be visible and not shown on the right side with scrollable cards
